[package]
name = "oracle"
version = "0.1.0"
authors = ["acc-server-admin"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
lazy_static = "1.4.0"
libc = "0.2"
